---
- hosts: all
  become: true
  tasks: 

  - name: install apache & php
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

