---
- hosts: all
  become: true
  tasks: 

  - name: remove apache & php
    ansible.builtin.apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
